<a href="https://colab.research.google.com/github/shanyuzhe/Data_Science_Notes/blob/main/numpy/100_Numpy_exercises_with_hint_ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)
(**hint**: np.zeros)

In [ ]:
zero = np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆)
(**hint**: size, itemsize)

In [ ]:
print(zero.size)
print(zero.itemsize)#每个元素占几个byte

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
(**hint**: array\[4\])

In [ ]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)
(**hint**: np.arange)

In [ ]:
array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)
(**hint**: array\[::-1\])

In [ ]:
array = array[::-1]
print(array)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
(**hint**: reshape)

In [ ]:
array = np.arange(9)
array = array.reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)
(**hint**: np.nonzero)

In [ ]:
array = np.array([1,2,0,0,4,0])
print(np.nonzero(array))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)
(**hint**: np.eye)

In [ ]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)
(**hint**: np.random.random)

In [ ]:
array = np.random.rand(3,3,3)
print(array)

[[[0.23058286 0.32669932 0.64842216]
  [0.67795656 0.3792635  0.02425771]
  [0.11398671 0.49651204 0.11730029]]

 [[0.07474429 0.65204511 0.62661771]
  [0.21192857 0.97646983 0.71812342]
  [0.53787908 0.24738449 0.19335798]]

 [[0.9796842  0.64053242 0.17126463]
  [0.81891482 0.57117173 0.79361837]
  [0.57447657 0.3139208  0.05000116]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
(**hint**: min, max)

In [ ]:
array = np.random.rand(10, 10)
print(np.max(array))
print(np.min(array))

0.9959060133408026
0.024163499413579315


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
(**hint**: mean)

In [ ]:
arr = np.random.random(30)
print(np.mean(arr ))

0.5253462116126321


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
arr = np.ones((10,10))
print(arr)
arr[1:-1,1:-1] = 0
print(arr)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
(**hint**: np.pad)

In [ ]:
print(arr)
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=1)
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 17. What is the result of the following expression? (★☆☆)
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)#nan运算后还是nan
print(np.nan == np.nan)#nan甚至不等于自己
print(np.inf > np.nan)#无法运算 逻辑返回False
print(np.nan - np.nan)#仍然是nan
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)#精度问题
#如果梯度爆炸出现nan，用torch.isnan()，而不能做逻辑比较

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
(**hint**: np.diag)

In [ ]:

arr = np.diag(np.arange(1,5),k=-1)#k<0 below the diagonal
print(arr)
arr = np.diag(np.arange(1,5),k=0)#k>0 above the diagnoal
#print(np.info(np.diag))
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
(**hint**: array\[::2\])

In [ ]:
arr = np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))


(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
(**hint**: np.tile)

In [ ]:
arr = np.array([[0,1],[1,0]])
arr = np.tile(arr,(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)
(**hint**: (x - mean) / std)

In [ ]:
arr = np.random.rand(5, 5)
arr = (arr - np.mean(arr)) / np.std(arr)
print(arr)


[[ 0.07685131 -0.74930931 -0.71042698 -0.35343339 -1.26670331]
 [ 1.93323876 -1.2866809  -1.07628205 -0.46051925 -0.99962394]
 [ 1.27555883  0.65451602  0.5686304  -0.66485027 -0.6660081 ]
 [ 0.01095935  1.19508538  1.40928251  1.56851736  0.73494126]
 [ 0.30344347  0.22010687  0.98381987 -1.36005744 -1.34105644]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
(**hint**: np.dtype)

In [ ]:
d_type = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(d_type)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
(**hint**: np.dot | @)

In [ ]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
c = np.dot(a,b)
print(c)
print(a@b)

[[0.95697433 0.8868482 ]
 [1.18804678 0.8029179 ]
 [0.92151975 0.77522818]
 [1.11492104 0.74502549]
 [0.82501377 0.71060093]]
[[0.95697433 0.8868482 ]
 [1.18804678 0.8029179 ]
 [0.92151975 0.77522818]
 [1.11492104 0.74502549]
 [0.82501377 0.71060093]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
(**hint**: >, <=)

In [ ]:
a = np.arange(10)
a[(a>3) & (a<=8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#最佳实践：始终使用 import numpy as np，然后显式调用 np.sum()。
#import *会覆盖原有sum
#第一个sum的意思是sum(0,1,2,3,4,-1)
#第二个是sum((0,1,2,3,4),axis = -1)


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)#虚数
print(Z/1/1)
#print(Z<Z>Z)#错误

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


/tmp/ipython-input-1729466501.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipython-input-1729466501.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipython-input-1729466501.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a = np.random.uniform(-10, +10, 10)
print(a)
print(np.copysign(np.ceil(np.abs(a)), a))
#copysign(a,b) b符号->a


[-7.02565756  6.39849518  5.39264198 -1.48051403 -4.37353056  0.62035161
 -7.53567838  2.95773281 -0.98026095  1.44891821]
[-8.  7.  6. -2. -5.  1. -8.  3. -1.  2.]


#### 30. How to find common values between two arrays? (★☆☆)
(**hint**: np.intersect1d)

In [ ]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(a)
print(b)
print(np.intersect1d(a,b))

[9 1 8 4 8 2 6 4 6 4]
[3 1 7 7 9 1 1 9 2 1]
[1 2 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all='ignore')
np.errstate(all='ignore')

#### 32. Is the following expressions true? (★☆☆)
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)
#np.sqrt是实数域内的 返回Nan
#np.emath.sqrt是虚数 返回1j

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
np.datetime64('today')
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today') + np.timedelta64(1))


2026-01-06
2026-01-08


np.datetime64('2026-01-08')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
D = np.arange('2016-07', '2016-08', dtype='datetime64[D]')#datetime64[D]，单位是day
print(D)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=B)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
a = np.random.random(10)
print(a)
print(np.floor(a))
print(np.ceil(a))
print(a.astype(int))
print(np.trunc(a))


[0.43758151 0.01578804 0.32989287 0.91751415 0.34574811 0.36605824
 0.21140846 0.9341611  0.68282062 0.34128713]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
(**hint**: np.arange)

In [ ]:
np.arange(5)
a = np.tile(np.arange(0,5),(5,1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
(**hint**: np.fromiter)

In [ ]:
np.fromiter(range(10),dtype=int)
#numPy 直接从迭代器（range）中一个一个地取数并填入数组。

#优点：不需要在内存中建立中间列表，极其节省内存。



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
(**hint**: np.linspace)

In [ ]:
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)
#从0~1生成11个数，endpoint不包含，再用切片把0去掉 得到10个数

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)
(**hint**: sort)

In [ ]:
a = np.random.random(10)
a.sort()
print(a)


[0.05753025 0.18824031 0.331595   0.34358484 0.36710957 0.41163373
 0.59160033 0.60469345 0.82352689 0.83151393]


#### 41. How to sum a small array faster than np.sum? (★★☆)
(**hint**: np.add.reduce)

In [ ]:
print(a)
np.add.reduce(a) #这里的reduce是归约的意思 直到最后一个结果

[0.05753025 0.18824031 0.331595   0.34358484 0.36710957 0.41163373
 0.59160033 0.60469345 0.82352689 0.83151393]


np.float64(4.551028296422722)

#### 42. Consider two random array A and B, check if they are equal (★★☆)
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a = np.random.random(10)
b = np.random.random(10)
print(a)
print(b)
print(np.allclose(a,b))#近似相等
print(np.array_equal(a,b))#绝对相等

[0.53029813 0.26365663 0.38087336 0.07998181 0.63888067 0.08860098
 0.71610754 0.39518366 0.45282164 0.26464329]
[0.84931166 0.78965468 0.22243542 0.1379625  0.50175018 0.01410591
 0.31747423 0.78488972 0.29484995 0.35865626]
False
False


#### 43. Make an array immutable (read-only) (★★☆)
(**hint**: flags.writeable)

In [1]:
arr = np.arange(10)
arr.flags.writeable = False
arr[0] = 1

NameError: name 'np' is not defined

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
(**hint**: np.sqrt, np.arctan2)

In [4]:
import numpy as np
arr = np.arange(20).reshape(10,2)
X,Y = arr[:,0],arr[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
T = np.degrees(T)
print(R)
print(T)

[ 1.          3.60555128  6.40312424  9.21954446 12.04159458 14.86606875
 17.69180601 20.51828453 23.34523506 26.17250466]
[90.         56.30993247 51.34019175 49.39870535 48.36646066 47.72631099
 47.29061004 46.97493401 46.73570459 46.5481577 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
(**hint**: argmax)

In [6]:
arr = np.random.random(10)
print(arr)
arr[np.argmax(arr)] = 0
print(arr)

[0.33775081 0.39080239 0.7294534  0.05327741 0.38947866 0.81079854
 0.49129076 0.72175827 0.28732058 0.79816089]
[0.33775081 0.39080239 0.7294534  0.05327741 0.38947866 0.
 0.49129076 0.72175827 0.28732058 0.79816089]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)
(**hint**: np.meshgrid)

In [8]:
arr = np.zeros((5,5),[('x',float),('y',float)])
print(arr)
arr['x'],arr['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(arr)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
(**hint**: np.subtract.outer)

In [11]:
x = np.random.randn(10)
y = np.random.randn(1,10)
print(x)
print(y)
c = 1 / np.subtract.outer(x,y)
print(c)

[-0.77205766  0.48024044 -0.69884076  0.52386677  0.43204663 -0.45486785
  1.24322873 -1.24445522 -0.91247076  1.08865274]
[[ 1.03670916 -0.37460584 -1.55534123  0.14931923  1.02830008 -0.48206712
  -0.12930585  0.49656694 -0.54518214 -0.58052004]]
[[[ -0.55286286  -2.51602824   1.27667686  -1.08533219  -0.55544516
    -3.44838833  -1.55581048  -0.78825524  -4.40770342  -5.22090647]]

 [[ -1.79704619   1.16980095   0.49126007   3.02186732  -1.82461894
     1.0391688    1.64056448 -61.25010457   0.9752077    0.94271988]]

 [[ -0.57618625  -3.08418358   1.16754168  -1.17902284  -0.57899158
    -4.61310709  -1.75581864  -0.83653468  -6.50793323  -8.45160542]]

 [[ -1.94991679   1.11299998   0.48095236   2.66988805  -1.9824226
     0.99410111   1.53098885  36.6302734    0.9354109    0.90547985]]

 [[ -1.65381506   1.23969123   0.50317304   3.53697585  -1.67713915
     1.09395575   1.7814119  -15.49899516   1.02330183   0.98758929]]

 [[ -0.67043136 -12.45919554   0.90869985  -1.6551165   -

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
(**hint**: np.iinfo, np.finfo, eps)

In [16]:
print(np.iinfo(np.int64))
print(np.iinfo(np.int32))
print(np.finfo(np.float32))
print(np.finfo(np.float64))
print(np.finfo(np.float16))
print(np.finfo(np.float128))



Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =

AttributeError: module 'numpy' has no attribute 'eps'

#### 49. How to print all the values of an array? (★★☆)
(**hint**: np.set\_printoptions)

In [18]:
a = np.random.random(10)
print(a)
np.set_printoptions(threshold=1<<30)
print(a)

[0.85058282 0.49184313 0.11797098 0.13011432 0.94274881 0.68041247
 0.1974829  0.32906358 0.8812032  0.15029376]
[0.85058282 0.49184313 0.11797098 0.13011432 0.94274881 0.68041247
 0.1974829  0.32906358 0.8812032  0.15029376]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
(**hint**: argmin)

In [20]:
a = np.random.random(30)
b = np.random.random(30)
print(a)
print(b)
print(np.argmin(np.abs(a-b)))

[0.657032   0.39185834 0.1737383  0.6852146  0.25102962 0.36457128
 0.10783223 0.76572737 0.03776569 0.21894139 0.60574381 0.20852852
 0.20342525 0.98243052 0.45149019 0.43849522 0.43951534 0.32010375
 0.85952702 0.9052674  0.31341278 0.14110539 0.26827693 0.59014794
 0.91932424 0.5706394  0.93114638 0.72903298 0.35113405 0.24975192]
[0.59169971 0.68198642 0.0296493  0.49823466 0.19091166 0.40168651
 0.72574902 0.01909647 0.94016668 0.22066471 0.13973863 0.8516385
 0.83787959 0.88277001 0.4794267  0.76961291 0.80544895 0.81669508
 0.59187139 0.58828673 0.5563337  0.73479349 0.5527906  0.1545753
 0.53754109 0.92514392 0.53949961 0.77171643 0.10380254 0.88617723]
9


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
(**hint**: dtype)

In [21]:
dtype = np.dtype([("position",[("x",float,1),("y",float,1)]),("color",[("r",float,1),("g",float,1),("b",float,1)])])
a = np.zeros(10,dtype)
print(a)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
(**hint**: np.atleast\_2d, T, np.sqrt)

In [24]:
a = np.random.rand(5,2)
print(a)
X,Y = np.atleast_2d(a[:,0],a[:,1])#变换成二维，一维数组默认行向量
D = np.sqrt((X-X.T)**2+(Y-Y.T)**2)#计算每个点到其他所有点的距离 触发广播
print(D)#D[0][1]表示第0个点到第1个点的距离
#一个行向量 减去一个列向量的广播 拿x举例 计算第一列距离时的x
#分别为x1 -> (x1,x2.....xn)的距离

[[0.10867471 0.66428729]
 [0.39127533 0.53031137]
 [0.494792   0.13170221]
 [0.95044603 0.21621757]
 [0.23265087 0.4406404 ]]
[[0.         0.31275015 0.65782477 0.95359605 0.25571082]
 [0.31275015 0.         0.41183123 0.64134763 0.18221581]
 [0.65782477 0.41183123 0.         0.46342576 0.40516759]
 [0.95359605 0.64134763 0.46342576 0.         0.75206083]
 [0.25571082 0.18221581 0.40516759 0.75206083 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
(**hint**: astype(copy=False))

In [27]:
a = np.random.random(10).astype(np.float32)
print(a)
a = a.astype(np.int32,copy=False)
print(a)#实际上不能，copy=False只有类型相同时可以真正in place

[0.20975994 0.7414555  0.8376887  0.16670516 0.54734635 0.72020304
 0.22121395 0.9406786  0.7946475  0.21907215]
[0 0 0 0 0 0 0 0 0 0]


#### 54. How to read the following file? (★★☆)
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [28]:
np.genfromtxt('test.txt',delimiter=',',dtype=np.int32)

FileNotFoundError: test.txt not found.

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
(**hint**: np.ndenumerate, np.ndindex)

In [33]:
a = np.arange(9).reshape(3,3)
print(a)
for index,value in np.ndenumerate(a):
    print(index,value)
for index in np.ndindex(a.shape):
    print(index,a[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)
(**hint**: np.meshgrid, np.exp)

In [47]:
a = np.random.random((5,5))
X,Y = np.meshgrid(np.linspace(-1,1,5),np.linspace(-1,1,5))
print(X)
print(Y)
D = np.sqrt(X**2+Y**2)
sigma,mu = 1.0,0.0
G = np.exp(-(D-mu)**2/(2*sigma**2))#高斯分布的那个指数部分
print(G)

[[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]
[[-1.  -1.  -1.  -1.  -1. ]
 [-0.5 -0.5 -0.5 -0.5 -0.5]
 [ 0.   0.   0.   0.   0. ]
 [ 0.5  0.5  0.5  0.5  0.5]
 [ 1.   1.   1.   1.   1. ]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. nan  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


/tmp/ipython-input-4279782803.py:7: RuntimeWarning: divide by zero encountered in divide
  G = np.exp(-(D-mu)**2/(2*sigma**2))#高斯分布的那个指数部分
/tmp/ipython-input-4279782803.py:7: RuntimeWarning: invalid value encountered in divide
  G = np.exp(-(D-mu)**2/(2*sigma**2))#高斯分布的那个指数部分


#### 57. How to randomly place p elements in a 2D array? (★★☆)
(**hint**: np.put, np.random.choice)

In [50]:
a = np.zeros(10)
print(a)
np.put(a,np.random.choice(range(10),5,replace=False),1)#replace表示是否抽样后放回
#replace=True 则有可能抽到同一个
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 1. 1. 0. 1. 0. 0. 0. 1.]


#### 58. Subtract the mean of each row of a matrix (★★☆)
(**hint**: mean(axis=,keepdims=))

In [54]:
a = np.random.random((5,5))
print(a)
b = a.mean(axis=1,keepdims=False)
print(b)
b = a.mean(axis=1,keepdims=True)
print(b)
print(a - b)

[[0.07509432 0.838641   0.7055539  0.5617418  0.11685094]
 [0.98595564 0.771537   0.71937439 0.84114581 0.42591172]
 [0.73792348 0.95771811 0.20334446 0.060744   0.30031595]
 [0.79963943 0.04943377 0.22453205 0.68736879 0.93269214]
 [0.89418901 0.39703869 0.0981356  0.75686109 0.65683951]]
[0.45957639 0.74878491 0.4520092  0.53873324 0.56061278]
[[0.45957639]
 [0.74878491]
 [0.4520092 ]
 [0.53873324]
 [0.56061278]]
[[-0.38448207  0.37906461  0.24597751  0.10216541 -0.34272545]
 [ 0.23717073  0.02275208 -0.02941052  0.0923609  -0.32287319]
 [ 0.28591428  0.50570891 -0.24866474 -0.3912652  -0.15169325]
 [ 0.26090619 -0.48929947 -0.31420118  0.14863555  0.39395891]
 [ 0.33357623 -0.16357409 -0.46247718  0.19624831  0.09622673]]


#### 59. How to sort an array by the nth column? (★★☆)
(**hint**: argsort)

In [55]:
a = np.random.random((5,5))
print(a)
print(a[:,1].argsort())
#a[:,1].argsort()返回按第一列排序的索引
print(a[a[:,1].argsort()])

[[0.02683537 0.11097673 0.33844601 0.64125951 0.70845831]
 [0.0134354  0.05397928 0.57488268 0.19756439 0.09261811]
 [0.05694256 0.93942817 0.75450988 0.04703949 0.76872841]
 [0.18481763 0.84274014 0.16030436 0.89553512 0.84208733]
 [0.99296005 0.90703909 0.86561951 0.84160193 0.23254951]]
[1 0 3 4 2]
[[0.0134354  0.05397928 0.57488268 0.19756439 0.09261811]
 [0.02683537 0.11097673 0.33844601 0.64125951 0.70845831]
 [0.18481763 0.84274014 0.16030436 0.89553512 0.84208733]
 [0.99296005 0.90703909 0.86561951 0.84160193 0.23254951]
 [0.05694256 0.93942817 0.75450988 0.04703949 0.76872841]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)
(**hint**: any, ~)

In [57]:
a = np.random.randint(0,3,(3,10))
print(a)
print((~a.any(axis=0)).any())
#沿着纵轴方向看看有没有活的 再取反 此时如果有空列的话就存在1
#最外面再套个any 只要有1个空列就是 True

[[2 2 1 1 2 0 2 2 0 0]
 [2 0 1 0 1 1 1 2 2 1]
 [2 0 0 2 2 1 2 2 1 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)
(**hint**: np.abs, argmin, flat)

In [59]:
a = np.random.random(10)
print(a)
b = 0.5
print(np.abs(a-b).argmin())
print(a[np.abs(a-b).argmin()])

[0.59776933 0.74791105 0.09253961 0.14939362 0.78093791 0.91607628
 0.83294552 0.31509282 0.97983427 0.52444565]
9
0.5244456520171922


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
(**hint**: np.nditer)

In [64]:
a = np.random.rand(1,3)
b = np.random.rand(3,1)
print(a)
print(b)
for x,y in np.nditer([a,b]):
    print(x+y)

[[0.89614922 0.45102943 0.70999213]]
[[0.66342414]
 [0.69433701]
 [0.83566867]]
1.5595733649902725
1.1144535684064611
1.373416272138757
1.590486230192793
1.1453664336089813
1.4043291373412772
1.7318178909570472
1.2866980943732358
1.5456607981055317


#### 63. Create an array class that has a name attribute (★★☆)
(**hint**: class method)

In [70]:
import numpy as np

class NamedArray(np.ndarray):
    # 1. __new__: 负责“生孩子”
    # 当你显式调用 NamedArray([1,2], name="A") 时触发
    def __new__(cls, array, name="no name"):
        # 将输入的普通数据(array)转换成标准数组，并强行转换(view)成当前类(cls)
        obj = np.asarray(array).view(cls)

        # 给新诞生的对象赋予属性
        obj.name = name

        # 返回这个造好的对象
        return obj

    # 2. __array_finalize__: 负责“遗传基因”
    # 当数组被切片、运算、或者做视图转换(view)时触发
    def __array_finalize__(self, obj):
        # 情况A: 如果是显式调用 __new__ 创建的，obj 是 None。
        # 因为 __new__ 里已经处理好属性了，这里直接跳过。
        if obj is None: return

        # 情况B: 如果是通过切片(如 b = a[:])创建的。
        # 此时 self 是新数组 b，obj 是老数组 a。
        # 我们要从老数组(obj)里把 'name' 属性抄过来给新数组(self)。
        # getattr(对象, '属性名', '默认值'): 防止 obj 只是个普通数组没有 name 属性
        self.name = getattr(obj, 'name', "no name")

# --- 测试代码 ---

# 1. 显式创建（触发 __new__）
a = NamedArray(np.arange(5), name="原始数组A")
print(f"a 的名字: {a.name}")
# 输出: a 的名字: 原始数组A

# 2. 切片创建（触发 __array_finalize__）
# 注意：这里没有调用 NamedArray(...)，而是直接切片
b = a[1:3]
print(f"b 的名字: {b.name}")
# 输出: b 的名字: 原始数组A (成功遗传了！)

# 3. 视图转换（触发 __array_finalize__）
# 把一个普通数组看作 NamedArray
c = np.array([1, 2]).view(NamedArray)
print(f"c 的名字: {c.name}")
# 输出: c 的名字: no name (因为原数组没有name，使用了默认值)

a 的名字: 原始数组A
b 的名字: 原始数组A
c 的名字: no name


In [68]:
class MobilePhone:
    # 1. 这里的 cls 代表 MobilePhone 这个类本身（工厂）
    def __new__(cls, color):
        print(f"步骤1 [__new__]: 工厂 ({cls.__name__}) 正在制造手机硬件...")

        # 真正创建对象的一步
        instance = super().__new__(cls)

        print(f"  -> 手机硬件造好了！内存地址是: {id(instance)}")
        # 必须把造好的手机返回去，才能进下一步
        return instance

    # 2. 这里的 self 代表刚才造好的那台手机
    def __init__(self, color):
        print(f"步骤2 [__init__]: 用户拿到手机 ({id(self)})，正在给外壳喷漆...")
        self.color = color
        print(f"  -> 喷漆完成！颜色是 {self.color}")

# 开始购买
print("--- 准备下单 ---")
my_phone = MobilePhone("黑色")
print("--- 购买结束 ---")

--- 准备下单 ---
步骤1 [__new__]: 工厂 (MobilePhone) 正在制造手机硬件...
  -> 手机硬件造好了！内存地址是: 132057138032432
步骤2 [__init__]: 用户拿到手机 (132057138032432)，正在给外壳喷漆...
  -> 喷漆完成！颜色是 黑色
--- 购买结束 ---


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
(**hint**: np.bincount | np.add.at)

--- 准备下单 ---
步骤1 [__new__]: 工厂 (MobilePhone) 正在制造手机硬件...
  -> 手机硬件造好了！内存地址是: 132057144141744
步骤2 [__init__]: 用户拿到手机 (132057144141744)，正在给外壳喷漆...
  -> 喷漆完成！颜色是 黑色
--- 购买结束 ---


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★)
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★)
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★)
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★)
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array?
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★)
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
(**hint**: np.ascontiguousarray | np.unique)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
(**hint**: np.percentile)